### ISSUE TITLE
Compare ResourceEdit with QuickRes

### ISSUE THREAD

**Issue by scottmc** [HaikuArchives/ResourceEdit#1]
Compare ResourceEdit with QuickRes and see which if any features of QuickRes could/should be added to ResourceEdit.
http://www.angryredplanet.com/~hackbod/beos/quickres.html

**Comment by R4H33M** [comment]
From my comparison, I see these are the features QuickRes has that ResourceEdit doesn't:
- View and edit app icons with an inbuilt image editor
![image](https://user-images.githubusercontent.com/55973312/73056672-b0caed80-3ea0-11ea-91b8-752ea729735f.png)
- Easily change app flags
![image](https://user-images.githubusercontent.com/55973312/73056425-0bb01500-3ea0-11ea-8953-e669c682013c.png)
- View and edit app-version data, with a hex view
![image](https://user-images.githubusercontent.com/55973312/73055954-f1c20280-3e9e-11ea-89cf-048834662d14.png)
- Easily open recently opened files through the menu
- Edit resource types such as BRect and RGB colours, but through simple text editing (no colour picker)
![image](https://user-images.githubusercontent.com/55973312/73056554-68133480-3ea0-11ea-8b85-0eb519818e74.png)

Should I make PRs for these?

**Comment by scottmc** [comment]
Yes please.  These would make for good bite sized tasks, for anyone looking for something quick, easy, and these would be useful to have.

**Comment by R4H33M** [comment]
Done! As the second and the last point already exist as the issue #15, I did not create issues for them.
Does it look good?
