### ISSUE TITLE
App doesn't compile using make(Terminal Output Added)

### ISSUE THREAD

**Issue by ojasva** [HaikuArchives/ResourceEdit#2]
[terminalout.zip](https://github.com/HaikuArchives/ResourceEdit/files/2536095/terminalout.zip)

**Comment by bach5000** [comment]
@scottmc Got it working on x86_64! But... when I open an rsrc file nothing shows up?
I'm going to take a look at this and try to find out why.

**Comment by Zotyamester** [comment]
This should be closed.

**Comment by humdingerb** [comment]
Yep, thanks!
